"use client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/app/components/ui/button";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());
  return (
    <html lang="en">
      <body>
        <div
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <QueryClientProvider client={queryClient}>
            <header>
              <Link href="/">
                <Button className="bg-primary text-white hover:bg-primary/90 text-lg px-6 py-3">
                  main
                </Button>
              </Link>
              <Link href="/products">
                <Button className="bg-primary text-white hover:bg-primary/90 text-lg px-6 py-3">
                  Products
                </Button>
              </Link>
              <Link href="/cart">
                <Button className="bg-primary text-white hover:bg-primary/90 text-lg px-6 py-3">
                  Cart
                </Button>
              </Link>
            </header>
            {children}
          </QueryClientProvider>
        </div>
      </body>
    </html>
  );
}
